### ISSUE TITLE
adding `cohort_type` variable to `call_agenda()`

### ISSUE THREAD

**Issue by jules32** [Openscapes/kyber#62]
Hi! Noting this for whenever we're able to tackle it –

I suspect the duplication that @stefaniebutland is seeing [in this issue](https://github.com/Openscapes/cohort-planning/issues/176#issuecomment-1692466065) is due to the multiple titles for Call 1 (Column C in the [CohortRegistry](https://docs.google.com/spreadsheets/d/1Ys9KiTXXmZ_laBoCV2QWEm7AcnGSVQaXvm2xpi4XTSc/edit#gid=942365997)) that are for different `cohort_types`

**Comment by seankross** [comment]
Fixed in #80

**Comment by stefaniebutland** [comment]
@seankross I've reinstalled kyber since your updates, tested creating agenda and I still get duplication in Call title:

![Screenshot 2024-01-15 at 10 47 37 AM](https://github.com/Openscapes/kyber/assets/11927811/3160492c-0598-4b95-9d00-9a6024a0e4f7)

**Comment by stefaniebutland** [comment]
@jules32 I'm still seeing this after deleting and reinstalling Kyber, Apr 19, 2024. Can you please try creating an agenda and look for duplicated topics in heading?

**Comment by jules32** [comment]
Hi @stefaniebutland et al, I have just tested today after reinstalling R and kyber, and only see one header!

```
library(kyber)
library(googlesheets4)

kyber::call_agenda(
    registry_url = "https://docs.google.com/spreadsheets/d/1Ys9KiTXXmZ_laBoCV2QWEm7AcnGSVQaXvm2xpi4XTSc/edit#gid=942365997", 
    cohort_id = "2022-nasa-champions", 
    call_number = 3)
```    

<img width="915" alt="image" src="https://github.com/Openscapes/kyber/assets/5891909/80cee235-3a79-4132-97dd-7f97abfcbab6">

**Comment by stefaniebutland** [comment]
Thank you @jules32 ! Works for me now. Maybe I had forgotten to start new R session
